# Matrices and tensors - named, visualized

* [PiterPy Online, 3-6 Aug 2020](https://piterpy.com/en)
* Piotr Migdał, founder at [Quantum Flytrap](https://quantumgame.io/) / AI resercher at ECC Games
    * [p.migdal.pl](https://p.migdal.pl/), Twitter: [@pmigdal](https://twitter.com/pmigdal), [github.com/stared](https://github.com/stared)
* [talk link](https://piterpy.com/en/materials/2831#2831), [talk code]()
* interactive slides created with [Jupyter Notebook & RISE](https://github.com/damianavila/RISE)

## Abstract

In data science, we often work with numeric arrays: for signals, images, accounting data - input, output, everything. When we use Pandas (vs raw NumPy) we have named dimensions (rows and columns) plus an easy way to plot the numerical values.
In this talk, I will show how to go beyond that - how to name dimensions in 3 and more dimensional arrays for deep learning (with Named Tensors in PyTorch), how to visualize advanced operations in a simple way (using tensor diagrams) and how to plot complex numbers (for quantum computing).
I will give examples from two open-source projects I develop: https://github.com/Quantum-Game/bra-ket-vue and https://github.com/stared/pytorch-named-dims.

## Bio

Piotr Migdal

A deep learning specialist with a Ph.D. in quantum physics (from ICFO, Castelldefels).
He works on AI for content design and physics engine optimization in ECC Games, and develops Quantum Game with Photons - an open-source in-browser game with real quantum mechanics.
Piotr enjoys explaining complicated things in simple ways, ideally with interactive data visualizations. He develops livelossplot - a Python package for visualizing the training process in Jupyter Notebook.

In [1]:
import numpy
import pandas
print(numpy.__version__)
print(pandas.__version__)

1.18.1
1.0.1


## What is the matrix?

> *“The Matrix is everywhere. It's all around us,”* he explains to Neo.

<img src="imgs/matrix_rain_2.png" alt="Matrix rain of symbols" style="width: 80%;"/>

* In plain English?
* Well, it is a table with numbers.

## Outline

(warning: spoilers)

* Pure Python -> NumPy -> Pandas
* Some cool visualizations
* Step back to deep learning
* A pinch of quantum

I hope that you learn a tool or two, and how to approach 

## Pure Python

Does Python have support for matrices?

In [2]:
lol = [[1., 3., -1., 0.5, 2., 0.], [4., 0., 2.5, -4., 2., 1.], [1., 1., -1., 2, 2., 0.]]

`lol` stands for a list of lists. Nothing to laugh about.

In [3]:
# element
lol[1][3]

-4.0

In [4]:
# row
lol[1]

[4.0, 0.0, 2.5, -4.0, 2.0, 1.0]

In [5]:
# column
[row[2] for row in lol]

[-1.0, 2.5, -1.0]

### So

* You can use it
* You shouldn't

### Because

* Slow
* No easy way for typical operations
* No checks on numeric types...
* Or even if it is a table or not

## NumPy

Or **the** numerics backbone for Python.

In [6]:
import numpy as np

arr = np.array(lol)
arr

array([[ 1. ,  3. , -1. ,  0.5,  2. ,  0. ],
       [ 4. ,  0. ,  2.5, -4. ,  2. ,  1. ],
       [ 1. ,  1. , -1. ,  2. ,  2. ,  0. ]])

In [7]:
# element
arr[1,3]

-4.0

In [8]:
# row
arr[1]

array([ 4. ,  0. ,  2.5, -4. ,  2. ,  1. ])

In [9]:
# columns
arr[:, 1]

array([3., 0., 1.])

In [10]:
# operations
arr[2] - arr[0]

array([ 0. , -2. ,  0. ,  1.5,  0. ,  0. ])

In [11]:
## type
arr.dtype

dtype('float64')

### Good parts

* Fast (don't ever believe "but C++")
* A lot of numeric features (using `scipy`)

### But 

* What the hell the columns mean?!

## Pandas

(Note to oneself: resist any **pand**emia pun!)

In [12]:
import pandas as pd

df = pd.DataFrame(arr,
                  index=['Sasha', 'Alex', 'Kim'],
                  columns=['sweet', 'sour', 'salty', 'bitter', 'spicy', 'sugar'])
df 

sweet  sour  salty  bitter  spicy  sugar
Sasha    1.0   3.0   -1.0     0.5    2.0    0.0
Alex     4.0   0.0    2.5    -4.0    2.0    1.0
Kim      1.0   1.0   -1.0     2.0    2.0    0.0

In [13]:
df.loc['Alex', 'sweet']

4.0

In [14]:
df.loc[:, 'sweet']

Sasha    1.0
Alex     4.0
Kim      1.0
Name: sweet, dtype: float64

### Do we need anything more?

Hint:

> You think you own whatever data you loaded  
The Matrix is just a dead thing you can claim  
But I know every frame and row and column  
Has a type, has an API, has a name  

Answer:

Colors!

## S